### PR TITLE
514 - Paste issue since #479

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @gnodet mind to take a look ? I would like to release jline 3.14.1 with this fix as it impacts lot of Apache Karaf users.

**Comment by jbonofre** [comment]
@gnodet any update when you have a chance ? Thanks !

**Comment by gnodet** [comment]
Sorry, I missed the pings.  I'd like to fix the problem while still keeping the performance boost (pasting huge blocks was really slow).

**Comment by jbonofre** [comment]
@gnodet thanks. That's the purpose of my ping ;) Thanks again ;)

**Comment by gnodet** [comment]
This should now be fixed.  The problem was a missing implementation of `readBuffered`, see https://github.com/jline/jline3/commit/df9f1f9133539c6715b407e5dc80a280d75fd395#diff-60d315a4cec5eb41ed8b8fc94a96d4b1

**Comment by jbonofre** [comment]
@gnodet thanks, let me test.

**Comment by jbonofre** [comment]
I confirm that it works with command `df9f1f9`

**Pull request closed without merging**
