### PR TITLE
Check that input and output are ttys before building a system terminal

### LINKED ISSUE #612: JLine3 should not allow building a system terminal if input *or* output is not a tty

### PR DESCRIPTION
**Pull request by mattirn**
I have tested this in linux and Windows cmd/gitbash.
@gnodet please, could you check.

### CODE REVIEW

**Comment by gnodet** [comment]
I raised this issue when I tested the recent change in https://github.com/fusesource/jansi/blob/master/src/main/native/jansi_isatty.c#L47-L106 to detect redirected streams when running in Cygwin / msys.  The code has been fixed in Jansi so it should be available when using Jansi `CLibrary`, however, I think a similar code should be written for JNA.
I'll have a closer look at the proposed changes this week.

**Comment by mattirn** [comment]
Ok, if the problem is in Jansi/JNA then this will not certainly fix it.
This will simply add a check if input and output are connected to console before starting to create system terminal. 
Probably the change will make the code slightly more readable.
Please merge or drop this as you like. I'm well in both cases :).

**Comment by mattirn** [comment]
Added tty check when running in Cygwin / msys and using Jansi version >= 2.1

**Comment by turbanoff** [comment]
Can you please elaborate a bit the reason for this change?
I'm not an expert in JLine codebase. But this change broked autocompletion in our application after jline upgrade 3.16 -> 3.23 and I wounder what/how we should update our application. to get autocompletion back.

**Comment by gnodet** [comment]
@turbanoff it may be better to raise a new issue referencing that one, else it may get lost.  Could you provide detailed information, the output of the `org.jline.terminal.impl.Diag` class (java -jar jline-xxx.jar org.jline.terminal.impl.Diag` should work), and eventually a small reproducer project so that we can test the problem ?

**Comment by gnodet** [comment]
> ```
> Aug 08, 2023 3:10:52 PM org.jline.utils.Log logr
> WARNING: input is tty: {}true
> Aug 08, 2023 3:10:53 PM org.jline.utils.Log logr
> WARNING: output is tty: {}false
> Aug 08, 2023 3:10:54 PM org.jline.utils.Log logr
> WARNING: error is tty: {}false
> Aug 08, 2023 3:10:55 PM org.jline.utils.Log logr
> WARNING: Creating a dumb terminal
> java.lang.IllegalStateException: Unable to create a terminal
>         at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:375)
>         at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:314)
>         at org.jline.terminal.TerminalBuilder.terminal(TerminalBuilder.java:106)
>         at com.CoreLauncher.main(CoreLauncher.java:62)
> ```
> 
> 
>     
>   
> 
> When I evaluated `Diag.diag` in debugger:
> 
> 
> ```
> java.lang.NoClassDefFoundError: com/sun/jna/Platform
>         at org.jline.terminal.impl.jna.JnaNativePty.current(JnaNativePty.java:41)
>         at org.jline.terminal.impl.jna.JnaTerminalProvider.current(JnaTerminalProvider.java:33)
>         at org.jline.terminal.impl.jna.JnaTerminalProvider.posixSysTerminal(JnaTerminalProvider.java:84)
>         at org.jline.terminal.impl.jna.JnaTerminalProvider.sysTerminal(JnaTerminalProvider.java:55)
>         at org.jline.terminal.impl.Diag.testProvider(Diag.java:99)
>         at org.jline.terminal.impl.Diag.diag(Diag.java:57)
>         at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:557)
>         at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:314)
>         at org.jline.terminal.TerminalBuilder.terminal(TerminalBuilder.java:106)
>         at com.CoreLauncher.main(CoreLauncher.java:62)
> Caused by: java.lang.ClassNotFoundException: com.sun.jna.Platform
>         ... 24 more
> System properties
> =================
> os.name =         Linux
> OSTYPE =          null
> MSYSTEM =         null
> PWD =             /opt/ctdev
> ConEmuPID =       null
> WSL_DISTRO_NAME = null
> WSL_INTEROP =     null
> 
> OSUtils
> =================
> IS_WINDOWS = false
> IS_CYGWIN =  false
> IS_MSYSTEM = false
> IS_WSL =     false
> IS_WSL1 =    false
> IS_WSL2 =    false
> IS_CONEMU =  false
> IS_OSX =     false
> 
> JnaSupport
> =================
> StdIn stream =    false
> StdOut stream =   false
> StdErr stream =   false
> Unable to check stream names: java.lang.NoClassDefFoundError: com/sun/jna/Platform
> Unable to open terminal: java.lang.NoClassDefFoundError: com/sun/jna/Platform
> 
> JansiSupport
> =================
> StdIn stream =    true
> StdOut stream =   false
> StdErr stream =   false
> StdIn stream name =     /dev/pts/1
> StdOut stream name =    null
> StdErr stream name =    null
> Terminal size: Size[cols=200, rows=34]
> The terminal seems to work: terminal org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
> 
> Exec Support
> =================
> StdIn stream =    true
> StdOut stream =   false
> StdErr stream =   false
> StdIn stream name =     /dev/pts/1
> StdOut stream name =    null
> StdErr stream name =    null
> Terminal size: Size[cols=200, rows=34]
> The terminal seems to work: terminal org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.ExecPty
> ```
> 
> 
>     
>   
> 
> What application is trying to do is basically this:
> 
> 
> ```
>         Terminal terminal;
>         try {
>             terminal = TerminalBuilder.terminal();
>         } catch (IOException e) {
>             throw new RuntimeException(e);
>         }
> ```
> 
> 
>     
>   
> 
> And we get warning from `TerminalBuilder.terminal` that terminal is dumb one.

You must be doing something weird with the output stream / error stream.  Or maybe the JVM process is forked without inheriting the output / error stream ?  The first log statements seem to indicate they can't be recognised.

**Comment by turbanoff** [comment]
JVM application is executed by bash/python scripts. Output is also printed to the file via `tee` command
From `pstree --long -a` it looks like that:
```
  |   |                           `-python3 /opt/ctdev/system/libexec/dx_module.py -c run -d console
  |   |                               `-bash /opt/ctdev/system/libexec/start_app console
  |   |                                   |-bash /opt/ctdev/log/console.start.cmd
  |   |                                   |   `-java bla-bla-bla
  |   |                                   |       `-88*[{java}]
  |   |                                   `-tee -a /opt/ctdev/log/console.out
  ```
  
content of `console.start.cmd` looks like this:
```
#!/bin/bash
exec 2>&1
cd /opt/ctdev
export JAVA_HOME=/opt/java/java17
/opt/java/java17/bin/java bla-bla-bla
echo console exit code was $?
```
Perhaps this redirect `exec 2>&1` can be considered as _something weird_.
  
Anyway it works ok with jline 3.18. May be jline could provide some option to disable checks introduces in this PR?

**Pull request merged**
