### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by cstamas**
Update to Maven Wrapper 3.3.2 (no Maven version change) and build plugins bump.

Changes:
* maven wrapper 3.3.2 (w/ same Maven 3.9.6)
* maven plugins updates

### CODE REVIEW

**Review by jdillon — APPROVED** [review]
+1

**Comment by gnodet** [comment]
Why does dependabot not provide PR to update those plugins ?

**Comment by cstamas** [comment]
Unsure, and since this PR there are more plugins released...

**Comment by gnodet** [comment]
Everything has been upgrade with small PRs from dependabot.

**Pull request closed without merging**
