### PR TITLE
Build with Cmd on Windows

### PR DESCRIPTION
**Pull request by puskarpeter**
- attempts to switch from GitBash that has underlying slow IO operations

### CODE REVIEW

**Comment by puskarpeter** [comment]
Seems like this is not helping at all, since maybe the underlying process in the runner which spawns the run command is using GitBash (it builds slow when I open gitbash, then run cmd, and then inside there I build). Something strange is going on here.

**Comment by puskarpeter** [comment]
I think I figured it out, it was the PATH env variable leaking from the gitbash parent process.
Hopefully this should resolve the issue as after doing this in my VM it solved the problem.

**Comment by puskarpeter** [comment]
That's weird that it is still taking so long, this was enough on the VM to fix the problem

**Comment by puskarpeter** [comment]
We can try to print env before and after refresh to see what's changed and why it does not work here.

**Comment by puskarpeter** [comment]
https://github.com/puskarpeter/jline3/actions/runs/8848691008/job/24299004431

Here passing run in normal time.

Something in the PATH caused trouble, hence we clear it and only put necessary stuff on the PATH:
powershell for the wrapper script and JAVA_HOME for maven

**Comment by gnodet** [comment]
Thx a ton !

**Pull request merged**
