### PR TITLE
When adding spaces in place of tabs, calculate from start of line

### PR DESCRIPTION
**Pull request by PeterHolloway**
First go at a fix for #131. I appreciate that this may well be the wrong place to fix this and might have repercussions elsewhere. Let me know if there is better place for it.

### CODE REVIEW

**Comment by gnodet** [comment]
Any chance you could add a small unit test to check this behavior ?

**Comment by PeterHolloway** [comment]
Looking at this further, I'm not sure this is the right place for the fix. There are problems when appending a tab to an existing string. eg appending `foo\tbar` to `hello\n\tworld`, there is no way of knowing how long the last line is during the append without iterating over the full buffer again or adding a field just for expanding tabs.

I think the tab expansion would be better moved out of `append` and placed in the `toString` and `toAnsi` methods with tabs always being stored as `\t` internally. 

This would prevent the problems when `tabs` is set on a builder that already has text or changed between appends. eg

```java 
AttributedStringBuilder sb = new AttributedStringBuilder();
// tab is not expanded here
sb.append("tabbed\ttext");
sb.tabs(4);
// but is here (4 spaces)
sb.append("more\ttabs");
sb.tabs(5);
// and is here (5 spaces)
sb.append("different\ttabs");
```

If this is an acceptable change in behaviour, I will work on a PR for it.

Let me know.

**Comment by gnodet** [comment]
The problem of doing that is that it may break quite a lot of existing code which is using ```columnLength()```,  ```columnSubSequence()``` or ```columnSplitLength()``` from the AttributedStringBuilder.

Maybe we could more clearly document the current behaviour.  The example you describe can easily be solved by using:
```
AttributedStringBuilder sb = new AttributedStringBuilder();
sb.append("tabbed\ttext");
sb.append("more\ttabs");
sb.append("different\ttabs");

AttributedStringBuilder sb2 = new AttributedStringBuilder().tabs(5);
sb2.append(sb);
```

which could also be made available as a method:
```
public AttributedString expandTabs(int tabs) {
    return new AttributedStringBuilder().tabs(tabs).append(this).toAttributedString();
}
```

**Comment by PeterHolloway** [comment]
The example wasn't particularly something I was trying to do, just an occasion where the tab handling resulted in something counter intuitive.

I agree that the other methods would be affected by this change. I will see if I can think of a better way of handling them.

What is the expected behaviour of `columnLength`? at the moment it doesn't seem to work with newlines. eg `hello\nWorld` gives a columnLength of 9. Should this be 5? or 10?

I like the idea of expandTabs. Maybe that could be used internally before calculating the column widths?

**Comment by gnodet** [comment]
The ```columnLength``` and ```columnSubSequence``` methods do not have any meaning if the string spans multiple lines.  They are usually used after lines have been split.

**Comment by PeterHolloway** [comment]
I've updated the patch for now to just keep track of the last line length and use that for inserting tabs. I have also prevented the tab size from being changed after text has been added to keep the state consistent.

I will keep looking at this to see if there is a way of moving the tab expansion without breaking existing code (if you're happy for that change) but for now this would close #131.

**Pull request merged**
