### PR TITLE
20200603.lsc.pull

### PR DESCRIPTION
**Pull request by lscoughlin**
updated from comments on the list.
Had some issues trying to squash commits ( apologies - still learning )

### CODE REVIEW

**Comment by mattirn** [comment]
NP. I see that you have expanded your pull request from what I [proposed](https://groups.google.com/forum/#!msg/jline-users/kRE0RktfnIo/YKplkuQjBAAJ) in jline-users group. That makes it unnecessary difficult to find the modifications that were required when removing `execute()` method from `CommandRegistry` interface. In addition the pull request contains modifications (and errors) which I do not want to merge for example: `jline-graal.sh` that uses java to launch graal demo. Graal demo has been added to demonstrate how JLine can be used in [GraalVM](https://www.graalvm.org/), see details in [README](https://github.com/jline/jline3#jline-----).

When I proposed the modifications I was expecting to receive pull request something like this #543.

**Comment by lscoughlin** [comment]
No worries,
In learning and i hope you don't feel like I wasted your time.

Thanks for the feedback.

**Comment by mattirn** [comment]
No you haven't waste my time... Thanks to your observations we have made some good work...

**Comment by mattirn** [comment]
Closed in  #543

**Pull request closed without merging**
